// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpGvXd_lPRDhBMeEVL5FBgM_gT6P2YhHw',
    appId: '1:1030692240767:web:390024b72f5173505b6e4a',
    messagingSenderId: '1030692240767',
    projectId: 'exercise8-f179e',
    authDomain: 'exercise8-f179e.firebaseapp.com',
    storageBucket: 'exercise8-f179e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4PtdPfv-80RS7uZLF8cSgYQEqfofgPeU',
    appId: '1:1030692240767:android:4ad50e7beeb1b29e5b6e4a',
    messagingSenderId: '1030692240767',
    projectId: 'exercise8-f179e',
    storageBucket: 'exercise8-f179e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA06QWoJAUWZSkRxr49TiDeZv_tnSrp2JA',
    appId: '1:1030692240767:ios:e88bb62fc87c48945b6e4a',
    messagingSenderId: '1030692240767',
    projectId: 'exercise8-f179e',
    storageBucket: 'exercise8-f179e.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA06QWoJAUWZSkRxr49TiDeZv_tnSrp2JA',
    appId: '1:1030692240767:ios:e88bb62fc87c48945b6e4a',
    messagingSenderId: '1030692240767',
    projectId: 'exercise8-f179e',
    storageBucket: 'exercise8-f179e.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
